### ISSUE TITLE
Add support for ARM architecture

### ISSUE THREAD

**Issue by eschizoid** [jpeffer/docker-alexa-hue#2]
The CPU architecture for Raspberry Pi is ARM rather than x86/x64 by Intel or AMD. Thus, this container is failing with the following error:

```
FATA[0003] Error response from daemon: Cannot start container 0f0fa3f8e510e53908e6a459e817d600b9649e621e7dede974d6a65761ad39e5: exec format error
```

**Comment by jpeffer** [comment]
The base image of this container is Ubuntu 14.04 LTS. In order to support ARM architectures, a new container would be necessary. Unfortunately, I do not had a Raspberry Pi device to build and test the container on, so I will not be able to support the creation of a new container. If at some point I do acquire a pi to play with, I will look into creating a docker image to support alexa-hue.
